import { CarModelSmokeMeter } from '../carmodelsmokemeters/carmodelsmokemeter.model';
import { Tester } from '../testers/tester.model';

export class CarPostDataSmokeMeter {
  Id: number;
  DateTime: Date;
  Number: string;
  DOPOL1: string;
  DOPOL2: string;
  MIN_TAH: number;
  MIN_CO: number;
  MIN_CH: number;
  MIN_CO2: number;
  MIN_O2: number;
  MIN_L: number;
  MAX_TAH: number;
  MAX_CO: number;
  MAX_CH: number;
  MAX_CO2: number;
  MAX_O2: number;
  MAX_L: number;
  ZAV_NOMER: number;
  K_1: number;
  K_2: number;
  K_3: number;
  K_4: number;
  K_SVOB: number;
  K_MAX: number;
  MIN_NO: number;
  MAX_NO: number;
  CarModelSmokeMeterId: bigint;
  CarModelSmokeMeter: CarModelSmokeMeter;
  Temperature: number;
  Pressure: number;
  GasSerialNumber: number;
  GasCheckDate: Date;
  MeteoSerialNumber: number;
  MeteoCheckDate: Date;
  TestNumber: number;
  TesterId: bigint;
  Tester: Tester;
}
